---
- name: rabbitmq
  hosts: rabbitmq
  become: yes

  vars:
    - logical_volumes:
      - { lv_name: lv_lib, lv_size: 3g }
      - { lv_name: lv_log, lv_size: 3g }
    - pkg_names:
      - { repo_name: rabbitmq, pkg_name: rabbitmq-server, pkg_version: v3.8.x }
      - { repo_name: rabbitmq-erlang, pkg_name: erlang, pkg_version: 23 }

  roles:
    - centos7_rabbitmq

- name: prometheus
  hosts: prometheus
  become: yes

  vars:
    - logical_volumes:
      - { lv_name: lv_lib, lv_size: 9g }
      - { lv_name: lv_log, lv_size: 9g }

  roles:
    - centos7_prometheus